### ISSUE TITLE
banner size issue

### ISSUE THREAD

**Issue by PradoParking** [Explore-In-HMS/huawei.ads.admob_mediation#24]
https://we.tl/t-9iLXwW6g9m
;;

**Comment by GenarC** [comment]
@PradoParking , unfortunatelly the link is expired, please can you provide details here?

**Comment by GenarC** [comment]
#[1.2.15](https://github.com/Explore-In-HMS/huawei.ads.admob_mediation/releases/tag/1.2.15)
Ovesized issue resolved
