### ISSUE TITLE
Ads SDK version is outdated

### ISSUE THREAD

**Issue by megaacheyounes** [Explore-In-HMS/huawei.ads.admob_mediation#34]
Hi, I can see that you're using old Ads SDK https://github.com/Explore-In-HMS/huawei.ads.admob_mediation/blob/develop/under-20/admob_mediation/build.gradle#L67

As you know old HMS SDK was banned by Google, isn't it important to keep the SDK updated to latest version to ensure compliance with Google's T&C and Privacy policy, also that dependency seems to be deprecated and there are two new dependencies with: `ads-prime` and `ads-lite` , while the one you have in this repo `ads` does NOT exist anymore in the official documentation: https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/publisher-service-version-change-history-0000001050066909 

Please look into in timely manner

**Comment by megaacheyounes** [comment]
just checked version 2.0.2 (https://github.com/Explore-In-HMS/huawei.ads.admob_mediation/tree/2.0.2) and it has Ads kit version that's complaint with Play Store, but having `develop/under-20` as default branch is a misleading, it should NOT be the default branch, also your `main` branch is outdated!

**Comment by megaacheyounes** [comment]
just checked version 2.0.2 (https://github.com/Explore-In-HMS/huawei.ads.admob_mediation/tree/2.0.2) and it has Ads kit version that's complaint with Play Store, but having develop/under-20 as default branch is a misleading, it should NOT be the default branch, also your main branch is outdated!

**Comment by GenarC** [comment]
@megaacheyounes, 
Hi, thanks for the warning and suggestions. After Google updated and upgraded its mediation interface and framework, the development of Huawei Admob mediation library v2.x.x version started. For the current time being, there are still lots of developers still using the old AdMob library version. Therefore our default branch is under-20.  However, It is already on our time plan and soon we will select "dev" branch as default and the main version as 2.x.x, as you suggested

**Comment by megaacheyounes** [comment]
Will developers who publish their app to play store with Huawei Admob mediation library v1.x.x risk getting their app banned from playstore?

**Comment by GenarC** [comment]
For old versions, this may be the case. However, for the last 2-3 releases of the 1.x.x versions, PlayStore warning issue is solved. Also while integrating Huawei libraries, please use the latest version of AppGallery and HMS Kit versions to solve PlayStore warnings and errors. 

Even for developers who use an old version of the mediation library, using up-to-date Huawei Ads and App Gallery dependency solves the PlayStore issue.
