### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by khizar1556** [Explore-In-HMS/huawei.ads.admob_mediation#4]
I put this in my flutter app 
AdMob report showing custom event request and impression but when i go to huawaii ads reports it shows nothing .

**Comment by yunusemrepekguc** [comment]
Dear developer,

First of all, please make sure that the integration part is correct and then you can successfully receive ads. Dedicated ad unit IDs could be used to test the integration (this avoids invalid ad clicks during the test), and if test ads could be received that means integration has no issue. Please check the following related documentation for testing;

- [Banner Ads](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/publisher-service-banner-0000001050066915)
- [Interstitial Ads](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/publisher-service-interstitial-0000001050064970)
- [Rewarded Ads](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/publisher-service-reward-0000001050066917)
- [Native Ads](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/publisher-service-native-0000001050064968)

Before releasing your app, sign in to [HUAWEI Ads Publisher Console](https://developer.huawei.com/consumer/en/service/ads/publisher/html/index.html?lang=en), apply for a formal ad unit ID, and replace the test ad unit ID with the formal one. For details, please refer to [Adding/Enabling an Ad Unit](https://developer.huawei.com/consumer/en/doc/distribution/monetize/addunit-0000001051321846) and make sure that the ad unit is _valid_.

If the integration and ad unit creation parts are correct, you can be able to view informative graphs and reports on the [HUAWEI Ads Publisher Console](https://developer.huawei.com/consumer/en/monetize/).

- **Dashboard page**
View revenue data and data chart.

- **My reports page** 
View the reports based on the filter criteria.

Please check the following documentation for more details;
[Data Reports on Huawei Ads Publisher Console](https://developer.huawei.com/consumer/en/doc/distribution/monetize/report-0000001051321848)

**Comment by khizar1556** [comment]
I already integrate all the steps. I also change the test ad id to my original ad id if you want screenshot i will give it to you but not ads are showing

**Comment by cagataykizildag** [comment]
You can refer to this medium post to verify the solution. 

https://medium.com/huawei-developers/how-to-use-huawei-ads-with-admob-mediation-377bdc1ba01c
