### ISSUE TITLE
Library is using deprecated consent library

### ISSUE THREAD

**Issue by paolo-ermit** [Explore-In-HMS/huawei.ads.admob_mediation#5]
*com.github.Explore-In-HMS:huawei.ads.admob_mediation:1.2.8*  is using *com.google.android.ads.consent:consent-library:1.0.8*

This is problematic for 2 reasons:
- the first one is that *com.google.android.ads.consent:consent-library* is deprecated (as it is not IAB compliant) in favor of  *com.google.android.ump:user-messaging-platform*
- the second one is that *com.google.android.ads.consent:consent-library:1.0.8* uses *com.android.support:appcompat-v7:28.0.0*, that is deprecated in favor of AndroidX libraries

**Comment by yunusemrre** [comment]
Dear developer, we will consider and update the related dependency in the next version.

**Comment by yunusemrre** [comment]
Dear developer,

**Comment by yunusemrepekguc** [comment]
Dear developer,

After review, we will update the relevant libraries in the next version.

Thank you for your feedback.
